# Generated by Django 4.0.6 on 2022-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='shop/images/home_gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='image_low',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image_mid',
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
