# Generated by Django 4.0.6 on 2022-08-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_homeimage_remove_home_image_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_img', to='shop.home'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
