# Generated by Django 4.0.6 on 2022-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_homeimage_home_homeimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_main',
            field=models.ImageField(null=True, upload_to='shop/images/home_gallery'),
        ),
        migrations.AddField(
            model_name='home',
            name='image_second',
            field=models.ImageField(null=True, upload_to='shop/images/home_gallery'),
        ),
        migrations.AddField(
            model_name='home',
            name='image_third',
            field=models.ImageField(null=True, upload_to='shop/images/home_gallery'),
        ),
        migrations.DeleteModel(
            name='HomeImage',
        ),
    ]
