# Generated by Django 4.0.6 on 2022-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sizevariants_product_num_available_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='shop.sizevariants'),
        ),
        migrations.AlterField(
            model_name='sizevariants',
            name='size',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
