# Generated by Django 4.0.6 on 2022-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_size_productsize_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
