# Generated by Django 4.0.6 on 2022-08-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productsize_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_available',
        ),
    ]
